name: myapp
description: "Learn"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:
  go_router: ^14.8.1
  carousel_slider: ^5.0.0

  lottie:
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  uuid: ^4.5.1
  cached_network_image: ^3.3.0 # Moved from dev_dependencies
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.6.0
  curved_navigation_bar: ^1.0.6
  flutter_stripe: ^11.4.0
  provider: ^6.1.2
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  animations: ^2.0.11
  shared_preferences: ^2.5.2
  qr_flutter: ^4.1.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_firebase_chat_core: ^1.6.8
  http: ^1.3.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adding asset directory for images
  assets:
    - assets/
    - assets/ring_o.png
    - assets/userType.jpg
    - assets/BUser.jpg
    - lib/Icons/
    - lib/animations/
