name: myapp
description: "Learn"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:
  go_router: ^12.1.1
  firebase_core: ^3.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adding asset directory for images
  assets:
    - assets/
    - assets/ring_o.png
    - assets/BUser.jpg
    - lib/Icons/
