name: myapp
description: "Learn"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:
  go_router: ^12.1.1

  lottie:
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  uuid: ^4.5.1
  cached_network_image: ^3.3.0  # Moved from dev_dependencies
  smooth_page_indicator: ^1.0.0
  flutter_riverpod: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adding asset directory for images
  assets:
    - assets/
    - assets/ring_o.png
    - assets/userType.jpg
    - assets/BUser.jpg
    - lib/Icons/
    - lib/animations/
